# Generated by Django 4.0.3 on 2022-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('author', models.CharField(choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
